EDTESP.Web/Controllers/LoginController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Web.Security;
using EDTESP.Application;
using EDTESP.Application.Interfaces;
using EDTESP.Domain.Entities;
using EDTESP.Domain.Repositories;
using EDTESP.Web.Helpers;
using EDTESP.Web.ViewModels;

namespace EDTESP.Web.Controllers
{
    public class LoginController : Controller
    {
        private IUsuarioAppService _userAppSvc;

        public LoginController(IUsuarioAppService userAppSvc)
        {
            _userAppSvc = userAppSvc;
        }

        [AllowAnonymous]
        public ActionResult Index()
        {
            return View();
        }

        [AllowAnonymous]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Index(LoginViewModel model, string returnUrl = null)
        {
            try
            {
                if(!ModelState.IsValid)
                    throw new Exception("Todos os campos são necessários");

                var usr = _userAppSvc.Autenticar(model.Usuario, model.Senha);

                if(usr == null)
                    throw new Exception("usuário e/ou senha inválidos");

                FormsAuthentication.SetAuthCookie(usr.Login,true);
                Session["Usuario"] = usr;

                returnUrl = !string.IsNullOrEmpty(returnUrl) ? returnUrl : FormsAuthentication.DefaultUrl;
                return Redirect(returnUrl);
            }
            catch (Exception ex)
            {
                ModelState.AddModelError(string.Empty, ex.Message);
                return View(model);
            }
        }

        [AllowAnonymous]
        public ActionResult Logout()
        {
            Session.Abandon();
            Session.Clear();
            FormsAuthentication.SignOut();
            return Redirect(FormsAuthentication.LoginUrl);
        }
    }
}

EDTESP.Web/Controllers/RelatoriosController.cs
using EDTESP.Web.Helpers;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using EDTESP.Web.ViewModels.Relatorios;
using EDTESP.Application.Interfaces;
using EDTESP.Domain.Entities;
using AutoMapper;
using EDTESP.Domain.Entities.Relatorios;
using System.Net;
using EDTESP.Web.Filters;

namespace EDTESP.Web.Controllers
{
    [RibbonTab(Tab = "relatorios")]
    public class RelatoriosController : BaseController
    {
        private readonly IAppServiceBase<Vendedor> _appServiceBase;
        private readonly IComissaoInvidualAppService _comissaoInvidualAppService;
        private readonly IAdiantamentoSalarialAppService _adiantamentoSalarialAppService;
        private readonly IEstornoComissaoAppService _estornoComissaoAppService;
        private readonly IResumoVendaGeralAppService _resumoVendaGeralAppService;
        private readonly IResumoVendaRepresentanteAppService _resumoVendaRepresentanteAppService;
        private readonly ICobrancaClienteAppService _cobrancaClienteAppService;
        private readonly IAppServiceBase<Cliente> _appServiceBaseCliente;

        public RelatoriosController(IAppServiceBase<Status> appsvcBase, IAppServiceBase<Vendedor> appServiceBase, 
                                    IComissaoInvidualAppService comissaoInvidualAppService, 
                                    IAdiantamentoSalarialAppService adiantamentoSalarialAppService,
                                    IEstornoComissaoAppService estornoComissaoAppService, 
                                    IResumoVendaGeralAppService resumoVendaGeralAppService,
                                    IResumoVendaRepresentanteAppService resumoVendaRepresentanteAppService,
                                    ICobrancaClienteAppService cobrancaClienteAppService,
                                    IAppServiceBase<Cliente> appServiceBaseCliente) : base(appsvcBase)
        {
            _appServiceBase = appServiceBase;
            _comissaoInvidualAppService = comissaoInvidualAppService;
            _adiantamentoSalarialAppService = adiantamentoSalarialAppService;
            _estornoComissaoAppService = estornoComissaoAppService;
            _resumoVendaGeralAppService = resumoVendaGeralAppService;
            _resumoVendaRepresentanteAppService = resumoVendaRepresentanteAppService;
            _cobrancaClienteAppService = cobrancaClienteAppService;
            _appServiceBaseCliente = appServiceBaseCliente;
        }

        [EdtespAuthorize(Roles = "RCOMI")]
        public ActionResult ComissaoIndividual(int p = 1, int pp = 20, int vendedorId = 0, string emiIni = null, string emiFim = null)
        {
            var demiini = string.IsNullOrEmpty(emiIni) ? null : (DateTime?)Convert.ToDateTime(emiIni + " 00:00:00");
            var demifim = string.IsNullOrEmpty(emiFim) ? null : (DateTime?)Convert.ToDateTime(emiFim + " 23:59:59");

            ViewBag.Ini = demiini;
            ViewBag.Fim = demifim;

            var resultado = new List<ComissaoIndividual>();

            if ((demiini != null && demifim != null) || vendedorId > 0)
            {
                resultado = _comissaoInvidualAppService.RetornarDados(vendedorId,  
                                                                      demiini.HasValue? demiini.Value: DateTime.MinValue, 
                                                                      demifim.HasValue? demifim.Value: DateTime.MinValue);
            }

            var resultadoViewModel = Mapper.Map<List<ComissaoIndividual>, List<ComissaoIndividualViewModel>>(resultado);

            ViewBag.vendedorId = this.RetornarVendedores(vendedorId);

            if(resultadoViewModel != null && resultadoViewModel.Any())
            {
                ViewBag.ValorTotalContrato = resultadoViewModel.Sum(s => s.ValorFinal);
                ViewBag.TotalContratos = resultadoViewModel.Count();
                ViewBag.TotalComissao = resultadoViewModel.Sum(s => s.ValorReceber);
            }

            ViewBag.TituloPdf = "Perído " + demiini + " à " + demifim;

            return View("ComissaoIndividual", resultadoViewModel);
        }

        private SelectList RetornarVendedores(int vendedorId)
        {
            var lista = _appServiceBase.List().OrderBy(v => v.Nome).ToList();

            lista.Add(new Vendedor() { VendedorId = 0, Nome = "Selecione..." });

            return new SelectList
           (
               lista,
               "VendedorId",
               "Nome",
               vendedorId
           );
        }

        [EdtespAuthorize(Roles = "RADS")]
        public ActionResult AdiantamentoSalarial(int p = 1, int pp = 20, int vendedorId = 0, string emiIni = null, string emiFim = null)
        {
            var demiini = string.IsNullOrEmpty(emiIni) ? null : (DateTime?)Convert.ToDateTime(emiIni + " 00:00:00");
            var demifim = string.IsNullOrEmpty(emiFim) ? null : (DateTime?)Convert.ToDateTime(emiFim + " 23:59:59");

            ViewBag.Ini = demiini;
            ViewBag.Fim = demifim;

            var resultado = new List<AdiantamentoSalarial>();

            if ((demiini != null && demifim != null) || vendedorId > 0)
            {
                resultado = _adiantamentoSalarialAppService.RetornarDados(vendedorId,
                                                                      demiini.HasValue ? demiini.Value : DateTime.MinValue,
                                                                      demifim.HasValue ? demifim.Value : DateTime.MinValue);
            }

            var resultadoViewModel = Mapper.Map<List<AdiantamentoSalarial>, List<AdiantamentoSalarialViewModel>>(resultado);

            ViewBag.vendedorId = this.RetornarVendedores(vendedorId);

            if(resultadoViewModel != null && resultadoViewModel.Any())
            {
                ViewBag.QuantidadeContrato = resultadoViewModel.Count();
                ViewBag.ValorTotalContrato = resultadoViewModel.Sum(s => s.ValorBase);
                ViewBag.ValorTotalComissao = resultadoViewModel.Sum(s => s.ValorReceber);
                ViewBag.ValorTotalAdiantamento = resultadoViewModel.Sum(s => s.ValorAdiantamento);
            }

            return View("AdiantamentoSalarial", resultadoViewModel);
        }

        [EdtespAuthorize(Roles = "RESTC")]
        public ActionResult EstornoComissao(int p = 1, int pp = 20, int vendedorId = 0, string emiIni = null, string emiFim = null)
        {
            var demiini = string.IsNullOrEmpty(emiIni) ? null : (DateTime?)Convert.ToDateTime(emiIni + " 00:00:00");
            var demifim = string.IsNullOrEmpty(emiFim) ? null : (DateTime?)Convert.ToDateTime(emiFim + " 23:59:59");

            ViewBag.Ini = demiini;
            ViewBag.Fim = demifim;

            var resultado = new List<EstornoComissao>();

            if ((demiini != null && demifim != null) || vendedorId > 0)
            {
                resultado = _estornoComissaoAppService.RetornarDados(vendedorId,
                                                                      demiini.HasValue ? demiini.Value : DateTime.MinValue,
                                                                      demifim.HasValue ? demifim.Value : DateTime.MinValue,
                                                                      DateTime.Now.Date);
            }

            var resultadoViewModel = Mapper.Map<List<EstornoComissao>, List<EstornoComissaoViewModel>>(resultado);

            ViewBag.vendedorId = this.RetornarVendedores(vendedorId);

            if (resultadoViewModel != null && resultadoViewModel.Any())
            {
                ViewBag.ValorTotalContrato = resultadoViewModel.Sum(s => s.ValorFinal);
                ViewBag.ValorTotalComissao = resultadoViewModel.Sum(s => s.ValorReceber);
                ViewBag.ValorTotalParcela = resultadoViewModel.Sum(s => s.ValorParcela);
            }

            return View("EstornoComissao", resultadoViewModel);
        }

        [EdtespAuthorize(Roles = "RRVG")]
        public ActionResult ResumoVendaGeral(int p = 1, int pp = 20, int vendedorId = 0, string emiIni = null, string emiFim = null)
        {
            var demiini = string.IsNullOrEmpty(emiIni) ? null : (DateTime?)Convert.ToDateTime(emiIni + " 00:00:00");
            var demifim = string.IsNullOrEmpty(emiFim) ? null : (DateTime?)Convert.ToDateTime(emiFim + " 23:59:59");

            ViewBag.Ini = demiini;
            ViewBag.Fim = demifim;

            var resultado = new List<ResumoVendaGeral>();

            if ((demiini != null && demifim != null) || vendedorId > 0)
            {
                resultado = _resumoVendaGeralAppService.RetornarDados(vendedorId,
                                                                      demiini.HasValue ? demiini.Value : DateTime.MinValue,
                                                                      demifim.HasValue ? demifim.Value : DateTime.MinValue);
            }

            var resultadoViewModel = Mapper.Map<List<ResumoVendaGeral>, List<ResumoVendaGeralViewModel>>(resultado);

            ViewBag.vendedorId = this.RetornarVendedores(vendedorId);

            if (resultadoViewModel != null && resultadoViewModel.Any())
                ViewBag.ValorTotalContrato = resultadoViewModel.Sum(s => s.ValorFinal);

            return View("ResumoVendaGeral", resultadoViewModel);
        }

        [EdtespAuthorize(Roles = "RRESV")]
        public ActionResult ResumoVendaRepresentante(int p = 1, int pp = 20, int vendedorId = 0, string emiIni = null, string emiFim = null)
        {
            var demiini = string.IsNullOrEmpty(emiIni) ? null : (DateTime?)Convert.ToDateTime(emiIni + " 00:00:00");
            var demifim = string.IsNullOrEmpty(emiFim) ? null : (DateTime?)Convert.ToDateTime(emiFim + " 23:59:59");

            ViewBag.Ini = demiini;
            ViewBag.Fim = demifim;

            var resultado = new List<ResumoVendaRepresentante>();

EDTESP.Web/Views/Shared/403.cshtml
@{
    ViewBag.Title = "Acesso Negado";
    ViewBag.SubTitle = "Você não possui acesso ao recurso solicitado";
}
@*<div class="row">
    <i class="fa fa-ban fa-5x"></i>
</div>*@

EDTESP.Web/Views/Shared/_DialogEmail.cshtml
<div class="dialog" data-role="dialog" id="modalEnvioEmail">
    <div class="dialog-title bg-lightGray">Envio de E-mail</div>
    <div class="dialog-content overflow">
        <form>

        </form>
    </div>
    <div class="dialog-actions">
        <button class="button secondary js-dialog-close">Cancelar</button>
        <button class="button primary">Enviar</button>
    </div>
</div>

EDTESP.Web/Views/Shared/_Layout.cshtml
@{
    var ctrl = ViewContext.Controller.ValueProvider.GetValue("controller")?.RawValue?.ToString();
    var tab = ViewBag.CurrentTab;
}
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no">
    <meta name="metro4:init" content="false">
    <meta name="metro4:locale" content="pt-BR">
    <meta name="metro4:week_start" content="0">
    <title>@ViewBag.Title</title>
    @*@Styles.Render("~/Content/bs4")
        @Styles.Render("~/Content/mdb")
        @Styles.Render("~/Content/fluent")*@
    @Styles.Render("~/Content/m4")
    @Styles.Render("~/Content/fa")
    @Styles.Render("~/Content/css")
    @RenderSection("styles", required: false)
</head>
<body>
    @Html.Partial("_menuSuperior")
    <div class="container-fluid">
        <h1 class="my-5">
            @ViewBag.Title
            <small>@Html.Raw(ViewBag.SubTitle)</small>
        </h1>
        @RenderBody()
    </div>

    <div class="dialog no-border no-shadow bg-transparent global-dialog" id="dlgAct"
         data-role="dialog"
         data-default-action="false">
        <div class="dialog-content d-flex flex-column flex-justify-center flex-align-center bg-transparent no-shadow w-auto">
            <div data-role="activity" data-type="cycle" data-style="color"></div>
        </div>
    </div>

    <script>
        window.METRO_LOCALE = "pt-BR";
    </script>
    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/m4")
    @Scripts.Render("~/bundles/dt")
    @Scripts.Render("~/scripts/defaultui.js")
    <script type="text/javascript">
        Metro.init();
        $(document).ready(function () {
            SelecionaRibbonTab('@tab');

            $("nav[data-role='ribbonmenu'] button").on('click',
                function() {
                    var href = $(this).data('href');

                    if (href == '' || href == undefined)
                        return;

                    window.location.href = href;
                });
        });
    </script>
    @RenderSection("scripts", required: false)
</body>
</html>

EDTESP.Web/Views/Shared/_LayoutLogin.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>EDTESP | @ViewBag.Title</title>
    @Styles.Render("~/Content/bs4")
    @Styles.Render("~/Content/fluent")
    @Styles.Render("~/Content/micon.min.css")
    @Styles.Render("~/Content/fa")
    @Styles.Render("~/Content/login.css")
    @RenderSection("styles", required: false)
</head>
<body class="text-center">
    @RenderBody()
    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bs4")
    @Scripts.Render("~/bundles/mdb")
    @RenderSection("scripts", required: false)
    <script type="text/javascript">
        $(document).ready(function () {
            
        });
    </script>
</body>
</html>

EDTESP.Web/Views/Shared/_Paginacao.cshtml
@{
    var p = (int)ViewBag.Pagina;
    var pp = (int)ViewBag.PorPagina;
    var termo = (string)ViewBag.Termo;
    var pgs = (int) ViewBag.Paginas;
    var total = (int) ViewBag.Total;

    var ctrl = ViewData["controller"]?.ToString();
    var act = ViewData["action"]?.ToString();

    var emiIni = ((DateTime?) ViewBag.Ini).HasValue ? ((DateTime) ViewBag.Ini).ToString("dd/MM/yyyy") : null;
    var emiFim = ((DateTime?)ViewBag.Fim).HasValue ? ((DateTime)ViewBag.Fim).ToString("dd/MM/yyyy") : null;
}
@if (total > 0)
{
    <nav aria-label="Page navigation example">
        <ul class="pagination no-gap flex-justify-center">
            <li class="page-item @(p <= 1 ? "disabled" : "")">
                <a class="page-link" href="@Url.Action(act, ctrl, new {p = p - 1, pp, termo, emiIni, emiFim})">
                    <i class="fa fa-arrow-left"></i>
                </a>
            </li>
            <li class="page-item disabled">
                <a class="page-link" href="#">
                    @p de @pgs
                </a>
            </li>
            <li class="page-item @(p >= pgs ? "disabled" : "")">
                <a class="page-link" href="@Url.Action(act, ctrl, new {p = p + 1, pp, termo, emiIni, emiFim})">
                    <i class="fa fa-arrow-right"></i>
                </a>
            </li>
        </ul>
    </nav>
}

EDTESP.Web/Views/Shared/_busca.cshtml
@using (Html.BeginForm())
{
    var ctr = ViewContext.Controller.ValueProvider.GetValue("controller").RawValue?.ToString();
    var act = ViewContext.Controller.ValueProvider.GetValue("action").RawValue?.ToString();
    var url = Url.Action(act, ctr);
    <input type="text" name="termo" placeholder="Busca" data-role="input" data-search-button="true" data-on-clear-click="window.location.href='@url'" value="@ViewBag.Termo" autocomplete="off"/>
}

EDTESP.Web/Views/Shared/_busca_data.cshtml
@{
    var ctr = ViewContext.Controller.ValueProvider.GetValue("controller").RawValue?.ToString();
    var act = ViewContext.Controller.ValueProvider.GetValue("action").RawValue?.ToString();
    var url = Url.Action(act, ctr);
    var dini = ((DateTime?)ViewBag.Ini).HasValue ? ((DateTime?)ViewBag.Ini).Value.ToString("dd/MM/yyyy") : "";
    var dfim = ((DateTime?)ViewBag.Fim).HasValue ? ((DateTime?)ViewBag.Fim).Value.ToString("dd/MM/yyyy") : "";
}
@using (Html.BeginForm())
{
    <input class="mb-2" type="text" name="termo" placeholder="Busca" data-role="input" value="@ViewBag.Termo" autocomplete="off" />
    <div class="inline-form mb-2 input-daterange">
        <label>Data de Criação De</label>
        <input type="text" name="emiini" id="dtIni" value="@dini" autocomplete="off">
        <label> Até </label>
        <input type="text" name="emifim" id="dtFim" value="@dfim" autocomplete="off">
    </div>

    <div class="mb-2">
        <button type="submit" class="button primary">Buscar</button>
        <button type="button" class="button secondary" onclick="window.location.href='@url'">Limpar</button>
    </div>
}

EDTESP.Web/Views/Shared/_menuSuperior.cshtml
@using EDTESP.Domain.Entities
@{
    var ctrl = ViewData["controller"]?.ToString();
    var act = ViewData["action"]?.ToString();

    var usr = ViewBag.Usuario as Usuario;

    if (usr == null)
    {
        usr = TempData["Usuario"] as Usuario;
    }
}
<nav data-role="ribbonmenu">
    <ul class="tabs-holder">
        <li class="static"><a href="@Url.Action("Index","Home")">Início</a></li>
        <li data-rb-tab="cadastros"><a href="#section-one">Cadastros</a></li>
        <li data-rb-tab="operacao"><a href="#section-two">Operação</a></li>
        <li data-rb-tab="financeiro"><a href="#section-three">Financeiro</a></li>
        <li data-rb-tab="relatorios"><a href="#section-four">Relatórios</a></li>
        <li class="static bg-red"><a href="@Url.Action("Logout","Login")">Sair</a></li>
    </ul>

    <div class="content-holder">
        <div class="section" id="section-one">
            <div class="group">
                <div class="ribbon-split-button">
                    <button class="ribbon-main" data-href="@Url.Action("Usuarios", "Cadastros")">
                        <span class="icon">
                            <span class="mif-users"></span>
                        </span>
                    </button>
                    <span class="ribbon-split dropdown-toggle">Usuários</span>
                    <ul class="ribbon-dropdown" data-role="dropdown" data-duration="100">
                        <li>
                            <a href="@Url.Action("Grupos", "Cadastros")">Grupos</a>
                        </li>
                        <li><a href="@Url.Action("Setores", "Cadastros")">Setores</a></li>
                        <li><a href="@Url.Action("Cargos", "Cadastros")">Cargos</a></li>
                        <li><a href="@Url.Action("Times", "Cadastros")">Times</a></li>
                    </ul>
                </div>

                <div data-role="buttonsGroup" data-cls-active="active">

                    <button class="ribbon-button" data-href="@Url.Action("Vendedores", "Cadastros")">
                        <span class="icon">
                            <span class="mif-users"></span>
                        </span>
                        <span class="caption">Vendedores</span>
                    </button>

                </div>

                <div class="ribbon-split-button">
                    <button class="ribbon-main" data-href="@Url.Action("Condicoes", "Cadastros")">
                        <span class="icon">
                            <span class="mif-money"></span>
                        </span>
                    </button>
                    <span class="ribbon-split dropdown-toggle">Cond. de Pgto.</span>
                    <ul class="ribbon-dropdown" data-role="dropdown" data-duration="100">
                        <li>
                            <a href="@Url.Action("Formas", "Cadastros")">Formas de Pgto.</a>
                        </li>
                    </ul>
                </div>

                <span class="title">Geral</span>
            </div>

            <div class="group">
                <div data-role="buttonsGroup" data-cls-active="active">

                    <button class="ribbon-button" data-href="@Url.Action("Index", "Clientes")">
                        <span class="icon">
                            <span class="mif-broadcast"></span>
                        </span>
                        <span class="caption">Clientes</span>
                    </button>

                </div>
                <span class="title">Clientes</span>
            </div>

            <div class="group">
                <div data-role="buttonsGroup" data-cls-active="active">

                    <button class="ribbon-button" data-href="@Url.Action("IntegrarClienteBraslink", "Clientes")">
                        <span class="icon">
                            <span class="mif-broadcast"></span>
                        </span>
                        <span class="caption">Enviar cliente para Braslink</span>
                    </button>

                </div>
                <span class="title">Braslink</span>
            </div>

            <div class="group">
                <div data-role="buttonsGroup" data-cls-active="active">

                    <button class="ribbon-button" data-href="@Url.Action("Feriados", "Cadastros")">
                        <span class="icon">
                            <span class="mif-calendar"></span>
                        </span>
                        <span class="caption">Feriados</span>
                    </button>

                    @*<button class="ribbon-button" data-href="@Url.Action("Empresas", "Cadastros")">
                    <span class="icon">
                        <span class="mif-user-check"></span>
                    </span>
                    <span class="caption">Cedente/Produto</span>
                </button>*@

                </div>
                <span class="title">Outros</span>
            </div>

            @*<div class="group">
            <div data-role="buttonsGroup" data-cls-active="active">

                <button class="ribbon-button" data-href="">
                    <span class="icon">
                        <span class="mif-cogs"></span>
                    </span>
                    <span class="caption">Configurações</span>
                </button>

            </div>
            <span class="title">Administração</span>
        </div>*@

        </div>
        <div class="section" id="section-two">
            <div class="group">
                <div data-role="buttonsGroup" data-cls-active="active">

                    <button class="ribbon-button" data-href="@Url.Action("Index", "Contratos")">
                        <span class="icon">
                            <span class="mif-dashboard"></span>
                        </span>
                        <span class="caption">Dashboard</span>
                    </button>

                    <button class="ribbon-button" data-href="@Url.Action("Novo", "Contratos")">
                        <span class="icon">
                            <span class="mif-add"></span>
                        </span>
                        <span class="caption">Novo Contrato</span>
                    </button>

                    <button class="ribbon-button" data-href="@Url.Action("EmAnalise", "Contratos")">
                        <span class="icon">
                            <span class="mif-file-empty"></span>
                        </span>
                        <span class="caption">Em Análise</span>
                    </button>

                    <button class="ribbon-button" data-href="@Url.Action("Aprovados", "Contratos")">
                        <span class="icon">
                            <span class="mif-file-play"></span>
                        </span>
                        <span class="caption">Aprovados</span>
                    </button>

                    <button class="ribbon-button" data-href="@Url.Action("Reprovados", "Contratos")">
                        <span class="icon">
                            <span class="mif-cross"></span>
                        </span>
                        <span class="caption">Reprovados</span>
                    </button>

                    <button class="ribbon-button" data-href="@Url.Action("Suspensos", "Contratos")">
                        <span class="icon">
                            <span class="mif-minus"></span>
                        </span>
                        <span class="caption">Suspensos</span>
                    </button>

                </div>
                <span class="title">Contratos</span>
            </div>
        </div>
        <div class="section" id="section-three">
            <div class="group">
                <div data-role="buttonsGroup" data-cls-active="active">

                    @*<button class="ribbon-button" data-href="@Url.Action("Index", "Financeiro")">
                        <span class="icon">
                            <span class="mif-dashboard"></span>
                        </span>
                        <span class="caption">Dashboard</span>
                    </button>*@

                    <button class="ribbon-button" data-href="@Url.Action("Index", "Financeiro")">
                        <span class="icon">
                            <span class="mif-money"></span>
                        </span>
                        <span class="caption">Contas a Receber</span>
                    </button>

                    <button class="ribbon-button" data-href="@Url.Action("EmAtraso", "Financeiro")">
                        <span class="icon">
                            <span class="mif-money"></span>
                        </span>
                        <span class="caption">Em Atraso</span>
                    </button>

                </div>
                <span class="title">Cobrança</span>
            </div>
            <div class="group">
                <div data-role="buttonsGroup" data-cls-active="active">

                    <button class="ribbon-button" data-href="@Url.Action("BoletosPendentes", "Financeiro")">
                        <span class="icon">
                            <span class="mif-file-text"></span>
                        </span>
                        <span class="caption">Boletos Pendentes de Envio</span>
                    </button>

                    <button class="ribbon-button" data-href="@Url.Action("Remessas", "Financeiro")">
                        <span class="icon">
                            <span class="mif-file-text"></span>
                        </span>
                        <span class="caption">Remessas (CNAB)</span>
                    </button>

                    <button class="ribbon-button" data-href="@Url.Action("ArquivoRetorno", "Financeiro")">
                        <span class="icon">
                            <span class="mif-file-text"></span>
                        </span>
                        <span class="caption">Arquivo de retorno</span>
                    </button>
                </div>
                <span class="title">Boletos</span>
            </div>
        </div>
        <div class="section" id="section-four">
            <div class="group">
                <div data-role="buttonsGroup" data-cls-active="active">
                    <button class="ribbon-button" data-href="@Url.Action("ComissaoIndividual", "Relatorios")">
                        <span class="icon">
                            <span class="mif-table"></span>
                        </span>
                        <span class="caption">Comissão individual</span>
                    </button>
                    <button class="ribbon-button" data-href="@Url.Action("AdiantamentoSalarial", "Relatorios")">
                        <span class="icon">
                            <span class="mif-table"></span>
                        </span>
                        <span class="caption">Adiantamento salarial</span>
                    </button>
                    <button class="ribbon-button" data-href="@Url.Action("EstornoComissao", "Relatorios")">
                        <span class="icon">
                            <span class="mif-table"></span>
                        </span>
                        <span class="caption">Estorno comissão</span>
                    </button>
                    <button class="ribbon-button" data-href="@Url.Action("ResumoVendaGeral", "Relatorios")">
                        <span class="icon">
                            <span class="mif-table"></span>
                        </span>
                        <span class="caption">Resumo venda geral</span>
                    </button>
                    <button class="ribbon-button" data-href="@Url.Action("ResumoVendaRepresentante", "Relatorios")">
                        <span class="icon">
                            <span class="mif-table"></span>
                        </span>
                        <span class="caption">Resumo venda representante</span>
                    </button>
                    <button class="ribbon-button" data-href="@Url.Action("CobrancaCliente", "Relatorios")">
                        <span class="icon">
                            <span class="mif-table"></span>
                        </span>
                        <span class="caption">Cobrança cliente</span>
                    </button>
                </div>
            </div>
        </div>
    </div>
</nav>
<div class="container-fluid bg-gray light p-2 clear">
    <div class="place-left">
        <p>
            Seja bem-vindo @Html.Raw(usr?.Nome)
        </p>
    </div>
    <div class="place-right">
        @*<a class="button alert mini" href="@Url.Action("Logout", "Login")">
            <span class="mif-exit"></span> Sair
        </a>*@
    </div>
</div>